### PR TITLE
COMSOC 2021

### PR DESCRIPTION
**Pull request by reshef24**

### CODE REVIEW

**Comment by Simon-Rey** [comment]
I'll take it over from here ;)

**Comment by Simon-Rey** [comment]
Ok I've merged but probably should not have done that. 

It seems you're exporting from WordPress but the file you export can only be used to import again in another WordPress instance...

**Comment by reshef24** [comment]
Hi Simon, I exported the COMSOC 21 website in xml (plus image files) and
uploaded it in my branch.
I am trying to follow Claude's instructions on how to import.

Reshef Meir
Associate Prof.
Decision and Data Science (formerly the Industrial Engineering and
Management department)
Technion-Israel Institute of technology
homepage <http://reshef.net.technion.ac.il/>

**Comment by Simon-Rey** [comment]
OK I have found a solution I think. Give me 5 minutes and I send you the link with everything.

**Comment by Simon-Rey** [comment]
https://comsoc-community.org/archive/comsoc-2021/

Is that all correct?

**Pull request merged**
